{% set name = "aws-shell" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-shell-{{ version }}.tar.gz
  sha256: fd1699ea5f201e7cbaacaeb34bf1eb88c8fe6dc6b248bce1b3d22b3e099a41e5

build:
  entry_points:
    - aws-shell = awsshell:main
    - aws-shell-mkindex = awsshell.makeindex:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python =2.7|>=3.3
    - pip
  run:
    - python =2.7|>=3.3
    - awscli >=1.16.10,<2.0.0
    - prompt_toolkit >=1.0.0,<1.1.0
    - boto3 >=1.9.0,<2.0.0
    - configobj >=5.0.6,<6.0.0
    - pygments >=2.1.3,<3.0.0

test:
  imports:
    - awsshell
  commands:
    - pip check
    - aws-shell --help
    - aws-shell-mkindex --help
  requires:
    - pip

about:
  home: https://github.com/awslabs/aws-shell
  summary: An integrated shell for working with the AWS CLI
  license: Apache-2.0
  license_file:
    - NOTICE.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - proinsias
